### ISSUE TITLE
UX: Show "countdown to live" timer for mints and auctions

### ISSUE THREAD

**Issue by publicworks-art** [abigpotostew/publicworks.art#6]
<img width="692" alt="Screenshot 2024-03-04 at 8 48 31 AM" src="https://github.com/abigpotostew/publicworks.art/assets/114435884/6ee6b22e-3682-4543-987d-73c41df7772a">

On the mint page, show a countdown to when the mint starts

**Comment by abigpotostew** [comment]
done :) 
<img width="708" alt="Screenshot 2024-04-03 at 2 07 00 PM" src="https://github.com/abigpotostew/publicworks.art/assets/292215/9a6a1f70-0d16-4e23-9e02-a367c7f6ee4c">
